name: my_expense
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none' 

environment:
  sdk: '>=3.0.0-191.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_extended: ^1.0.0
  dynamic_color: ^1.6.2
  sqflite: ^2.2.4+1
  sqflite_common_ffi: ^2.2.1+1
  sqlite3_flutter_libs: ^0.5.12
  intl: ^0.18.0
  desktop_window: ^0.4.0
  tuple: ^2.0.1
  fl_chart: ^0.60.0
  flutter_sticky_header: ^0.6.5
  fluttertoast: ^8.2.1
  home_widget: 
    path: ./vendor/home_widget
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.23.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
